### ISSUE TITLE
OpenSSL version? Not compiling with latest version 1.1.1g

### ISSUE THREAD

**Issue by plabon** [insanum/ecies#3]
Which version of openssl did you use? Does this solution works in latest version? I am failing to compile with 1.1.1g version.

**Comment by insanum** [comment]
It compiles with v1.1.1g on my system though there is a compile warning about RAND_pseudo_bytes being deprecated. `ossl` still runs ok.

**Comment by plabon** [comment]
I am getting the following error while running make command:

```
/tmp/cchgDDEW.o: In function `ec_key_public_key_to_bin':
ecies_openssl.c:(.text+0x8f): undefined reference to `EC_KEY_get0_group'
ecies_openssl.c:(.text+0x9f): undefined reference to `EC_KEY_get0_public_key'
ecies_openssl.c:(.text+0xa8): undefined reference to `BN_new'
ecies_openssl.c:(.text+0xb1): undefined reference to `BN_CTX_new'
ecies_openssl.c:(.text+0xc1): undefined reference to `BN_CTX_start'
ecies_openssl.c:(.text+0xe4): undefined reference to `EC_POINT_point2bn'
ecies_openssl.c:(.text+0xf0): undefined reference to `BN_num_bits'
ecies_openssl.c:(.text+0x123): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x143): undefined reference to `BN_bn2bin'
ecies_openssl.c:(.text+0x174): undefined reference to `BN_CTX_end'
ecies_openssl.c:(.text+0x180): undefined reference to `BN_CTX_free'
ecies_openssl.c:(.text+0x18c): undefined reference to `BN_clear_free'
/tmp/cchgDDEW.o: In function `ec_key_private_key_to_bin':
ecies_openssl.c:(.text+0x1b3): undefined reference to `EC_KEY_get0_private_key'
ecies_openssl.c:(.text+0x1c3): undefined reference to `BN_num_bits'
ecies_openssl.c:(.text+0x1f6): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x216): undefined reference to `BN_bn2bin'
/tmp/cchgDDEW.o: In function `ec_key_public_key_bin_to_point':
ecies_openssl.c:(.text+0x266): undefined reference to `EC_POINT_new'
ecies_openssl.c:(.text+0x289): undefined reference to `BN_bin2bn'
ecies_openssl.c:(.text+0x292): undefined reference to `BN_CTX_new'
ecies_openssl.c:(.text+0x2a2): undefined reference to `BN_CTX_start'
ecies_openssl.c:(.text+0x2bd): undefined reference to `EC_POINT_bn2point'
ecies_openssl.c:(.text+0x2c9): undefined reference to `BN_CTX_end'
ecies_openssl.c:(.text+0x2d5): undefined reference to `BN_CTX_free'
ecies_openssl.c:(.text+0x2e1): undefined reference to `BN_clear_free'
/tmp/cchgDDEW.o: In function `ecies_transmitter_generate_symkey':
ecies_openssl.c:(.text+0x340): undefined reference to `EC_KEY_new_by_curve_name'
ecies_openssl.c:(.text+0x350): undefined reference to `EC_KEY_generate_key'
ecies_openssl.c:(.text+0x35c): undefined reference to `EC_KEY_get0_group'
ecies_openssl.c:(.text+0x36c): undefined reference to `EC_GROUP_get_degree'
ecies_openssl.c:(.text+0x39f): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x3e5): undefined reference to `ECDH_compute_key'
/tmp/cchgDDEW.o: In function `ecies_receiver_generate_symkey':
ecies_openssl.c:(.text+0x458): undefined reference to `EC_KEY_get0_group'
ecies_openssl.c:(.text+0x470): undefined reference to `EC_GROUP_get_degree'
ecies_openssl.c:(.text+0x4a3): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x4e9): undefined reference to `ECDH_compute_key'
/tmp/cchgDDEW.o: In function `aes_gcm_256b_encrypt':
ecies_openssl.c:(.text+0x58a): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x5b9): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x5e3): undefined reference to `CRYPTO_malloc'
ecies_openssl.c:(.text+0x5f2): undefined reference to `EVP_CIPHER_CTX_new'
ecies_openssl.c:(.text+0x5fb): undefined reference to `EVP_aes_256_gcm'
ecies_openssl.c:(.text+0x61a): undefined reference to `EVP_EncryptInit_ex'
ecies_openssl.c:(.text+0x635): undefined reference to `RAND_pseudo_bytes'
ecies_openssl.c:(.text+0x65c): undefined reference to `EVP_EncryptInit_ex'
ecies_openssl.c:(.text+0x68c): undefined reference to `EVP_EncryptUpdate'
ecies_openssl.c:(.text+0x6b0): undefined reference to `EVP_EncryptUpdate'
ecies_openssl.c:(.text+0x6de): undefined reference to `EVP_EncryptFinal_ex'
ecies_openssl.c:(.text+0x712): undefined reference to `EVP_CIPHER_CTX_ctrl'
ecies_openssl.c:(.text+0x71e): undefined reference to `EVP_CIPHER_CTX_free'
```
